FROM node:20.9.0-alpine3.18

# definir o diretório de trabalho
WORKDIR /usr/src/web

# baixar e instalar dependências
COPY ./web/package.json /usr/src/web/package.json
COPY ./web/package-lock.json /usr/src/web/package-lock.json
RUN npm install

# adicionar rotas
EXPOSE 3000

# copiar arquivos do projeto
COPY ./web /usr/src/web