# Generated by Django 4.2.5 on 2023-11-13 23:29

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        UnaccentExtension()
    ]
