# Generated by Django 4.2.5 on 2023-11-06 13:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_department_name_remove_discipline__class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='classroom',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='class',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), size=None),
        ),
        migrations.AlterField(
            model_name='class',
            name='schedule',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='class',
            name='teachers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
