# Generated by Django 4.2.5 on 2023-11-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20231113_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='workload',
        ),
    ]
