# Generated by Django 4.2.5 on 2023-11-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_class_classroom_alter_class_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='_class',
            field=models.CharField(max_length=30),
        ),
    ]
