# Generated by Django 4.2.5 on 2023-11-25 03:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_class_workload'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='special_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='class',
            name='_class',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='class',
            name='classroom',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='class',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None),
        ),
        migrations.AlterField(
            model_name='class',
            name='schedule',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='class',
            name='teachers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None),
        ),
    ]
