# Generated by Django 4.2.5 on 2023-11-26 20:40

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_class_workload_class_special_dates_and_more'),
    ]
    
    operations = [
        CreateExtension("pg_trgm"),
        migrations.RunSQL(
            "CREATE TEXT SEARCH CONFIGURATION portuguese_unaccent( COPY = portuguese );"
        ),
        migrations.RunSQL(
            "ALTER TEXT SEARCH CONFIGURATION portuguese_unaccent "
            + "ALTER MAPPING FOR hword, hword_part, word "
            + "WITH unaccent, portuguese_stem;"
        )
    ]
