# Generated by Django 4.2.5 on 2023-11-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231126_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='unicode_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
