# Generated by Django 4.2.5 on 2023-11-28 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_class_special_dates'),
        ('api', '0005_discipline_unicode_name'),
    ]

    operations = [
    ]
