# Generated by Django 4.2.10 on 2024-02-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_schedule_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
